### ISSUE TITLE
Does `client.subscribe_invoices()` work?

### ISSUE THREAD

**Issue by fawkesley** [adrienemery/lnd-grpc-client#8] opened 2018-08-01 10:59 UTC
Hi, cool library, thanks!

I've been successfully using it for creating invoices, but when I iterate on `client.subscribe_invoices()` I don't get anything yielded at all when I create new invoices.

Have you had this working? Thanks!

**Comment by adrienemery** [comment] 2018-08-02 03:29
hi @paulfurley, I have had this working but will try repro to see if something has changed. 

Can you describe the setup you have that isn't working so I can try rerpo on my side. 

Thanks for bug report 👍

**Comment by ysangkok** [comment] 2018-10-11 17:11
@adrienemery Could you reproduce?

**Comment by adrienemery** [comment] 2018-10-12 04:01
@ysangkok no - I just ran this locally with latest lnd  (`Version: 0.5.0-beta commit=v0.5-beta-103-gb00e43eec1f19e55f910f7eb527bf7437b4069b4-dirty`)

```python
from lndgrpc import LNDClient

lnd = LNDClient("127.0.0.1:10009")

print('Listening for invoices...')
for invoice in lnd.subscribe_invoices():
    print(invoice)
```

When I generate invoices with `lncli` they get printed by the above code.

If there is a configuration that doesn't work please let me know and I can investigate. But for now I will close this since can't repro.

**Closed as completed by adrienemery** 2018-10-12 04:01 UTC
Labels: bug

**Comment by citizenanalog** [comment] 2021-02-02 00:50
Running a node on Polar/testnet, Python 3.8.1. 

I get no response from
```
for invoice in lnd.subscribe_invoices():
    print(invoice)
```

**Comment by adrienemery** [comment] 2021-02-02 18:46
@citizenanalog Just to rule out anything weird, are you able to connect to your LND node using other methods provided by the library?

**Comment by citizenanalog** [comment] 2021-02-02 21:06
Other methods (get_info, wallet_balance, list_invoices) working as expected.
